version: '3.7'

services:
  auth_service:
    build: ./auth-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://auth_db_username:auth_db_password@auth_db/auth_db_dev
    depends_on:
      - auth_db

  auth_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=auth_db_username
      - POSTGRES_PASSWORD=auth_db_password
      - POSTGRES_DB=auth_db_dev

volumes:
    postgres_data_auth: